[package]
name = "gitobi"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["alloc", "default"] }
gitwrap = { version = "0.11.0" }
base64 = { version = "0.22" }
itoa = "1.0.14"
ryu = "1.0.18"
